version: '3.8'

services:
  app:
    image: healthtrack-frontend-image
    container_name: healthtrack-frontend-container
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4173:4173